version: '3.8'

services:
	nginx:
		container_nme:
			-	nginx
		volumes:
			- wordpress: /var/www/wordpress
		build:
			context:
				- ./requirements/nginx
		ports:
			- "443:443"
		depends_on:
			- wordpress
		restart:
			- always
		env_file:
			- .env
		ports:
			- "443:443"
		restart:
			- on-failure
		networks:
			- inception

services:
	mariadb:
		container_name:
			- mariadb
		build:
			context:
				- ./requirements/mariadb
		env:
			- .env
		volumes:
			- mariadb: /var/lib/mysql
		restart:
			- unless-stopped
		networks:
			- inception
		expose:
			- "3306"

services:
	wordpress:
		container_name:
			- wordpress
		env_file:
			- .env
		volumes:
			- wordpress:/var/www/wordpress
		depends_on:
			- mariadb
		build:
			context:
				- ./requirements/wordpress
		restart:
			- on-failure
		expose:
			- "9000"
		networks:
			- inception

volumes:
	wordpress:
		driver: local
		driver_opts:
			type: 'none'
			o: 'bind'
			device: '/home/${USER}/data/wordpress'
	wordpress:
		driver: local
		driver_opts:
			type: 'none'
			o: 'bind'
			device: '/home/${USER}/data/mariadb'

networks:
	inception:
		driver: bridge
