version: '3.8'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - /var/lib/mysql
    restart: unless-stopped
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - /var/www/wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    restart: on-failure
    expose:
      - "9000"
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
        type: volumes
        o: bind
        device: './home/sleon/data/mysql'
  wordpress:
    driver: local
    driver_opts:
        type: volumes
        o: bind
        device: './home/sleon/data/wordpress'

networks:
  inception:
      driver: bridge
